# Generated by Django 3.0.4 on 2020-03-10 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200310_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, editable=False, max_length=150, unique=True),
        ),
    ]
