# Generated by Django 3.0.4 on 2020-03-10 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200310_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=uuid.UUID('96951690-62d4-11ea-a3c4-f40f2428bdb6'), editable=False, max_length=150, unique=True),
        ),
    ]
